version: '3.8'

services:
  credit_default_api:
    build: .
    container_name: credit_default_service
    restart: always
    ports:
      - "5000:5000"
    volumes:
      # Флаг :Z автоматически и безопасно настроит SELinux для этой папки
      - ./models:/app/models:Z
    environment:
      - PYTHONUNBUFFERED=1
